"$schema" = "./node_modules/wrangler/config-schema.json"

name = "cuan"
main = "src/index.ts"
# Set this to today's date
compatibility_date = "2026-09-03"
workers_dev = false

[[d1_databases]]
binding = "CLOUDFLARE_D1_BINDING_NAME"
database_name = "cuan"
database_id = "df371ae2-5683-4c6f-b0fd-91170cdc17b4"
migrations_dir = "drizzle"
